-- Generated by Oracle SQL Developer Data Modeler 4.0.1.836
--   at:        2016-11-14 12:52:25 EST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c


CREATE SEQUENCE READING_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1000000000000;


CREATE TABLE blood_pressure
  (
    reading_id  VARCHAR2 (20 CHAR) NOT NULL ,
    bp_high    	NUMBER ,
    bp_low 		NUMBER ,
    heart_rate  NUMBER ,
    measured_dt TIMESTAMP ,
    measured_by VARCHAR2 (200 CHAR) ,
    patient_id  VARCHAR2 (20 CHAR)
  ) ;
ALTER TABLE blood_pressure ADD CONSTRAINT blood_pressure_PK PRIMARY KEY ( reading_id ) ;

CREATE TABLE patient
  (
    patient_id    VARCHAR2 (20 CHAR) NOT NULL ,
    first_name    VARCHAR2 (200 CHAR) ,
    last_name     VARCHAR2 (200 CHAR) ,
    mobile        NUMBER ,
    email_address VARCHAR2 (50 CHAR)
  ) ;
ALTER TABLE patient ADD CONSTRAINT patient_PK PRIMARY KEY ( patient_id ) ;


